export const indianStates = [
  // States
  { label: 'Andhra Pradesh', value: 'Andhra Pradesh' },
  { label: 'Arunachal Pradesh', value: 'Arunachal Pradesh' },
  { label: 'Assam', value: 'Assam' },
  { label: 'Bihar', value: 'Bihar' },
  { label: 'Chhattisgarh', value: 'Chhattisgarh' },
  { label: 'Goa', value: 'Goa' },
  { label: 'Gujarat', value: 'Gujarat' },
  { label: 'Haryana', value: 'Haryana' },
  { label: 'Himachal Pradesh', value: 'Himachal Pradesh' },
  { label: 'Jharkhand', value: 'Jharkhand' },
  { label: 'Karnataka', value: 'Karnataka' },
  { label: 'Kerala', value: 'Kerala' },
  { label: 'Madhya Pradesh', value: 'Madhya Pradesh' },
  { label: 'Maharashtra', value: 'Maharashtra' },
  { label: 'Manipur', value: 'Manipur' },
  { label: 'Meghalaya', value: 'Meghalaya' },
  { label: 'Mizoram', value: 'Mizoram' },
  { label: 'Nagaland', value: 'Nagaland' },
  { label: 'Odisha', value: 'Odisha' },
  { label: 'Punjab', value: 'Punjab' },
  { label: 'Rajasthan', value: 'Rajasthan' },
  { label: 'Sikkim', value: 'Sikkim' },
  { label: 'Tamil Nadu', value: 'Tamil Nadu' },
  { label: 'Telangana', value: 'Telangana' },
  { label: 'Tripura', value: 'Tripura' },
  { label: 'Uttar Pradesh', value: 'Uttar Pradesh' },
  { label: 'Uttarakhand', value: 'Uttarakhand' },
  { label: 'West Bengal', value: 'West Bengal' },
  
  // Union Territories
  { label: 'Andaman and Nicobar Islands', value: 'Andaman and Nicobar Islands' },
  { label: 'Chandigarh', value: 'Chandigarh' },
  { label: 'Dadra and Nagar Haveli and Daman and Diu', value: 'Dadra and Nagar Haveli and Daman and Diu' },
  { label: 'Delhi', value: 'Delhi' },
  { label: 'Jammu and Kashmir', value: 'Jammu and Kashmir' },
  { label: 'Ladakh', value: 'Ladakh' },
  { label: 'Lakshadweep', value: 'Lakshadweep' },
  { label: 'Puducherry', value: 'Puducherry' },
];

export const cityDataByState = {
  'Andhra Pradesh': [
    { label: 'Visakhapatnam', value: 'Visakhapatnam' },
    { label: 'Vijayawada', value: 'Vijayawada' },
    { label: 'Guntur', value: 'Guntur' },
    { label: 'Nellore', value: 'Nellore' },
    { label: 'Kurnool', value: 'Kurnool' },
    { label: 'Rajahmundry', value: 'Rajahmundry' },
    { label: 'Tirupati', value: 'Tirupati' },
    { label: 'Kadapa', value: 'Kadapa' },
    { label: 'Anantapur', value: 'Anantapur' },
    { label: 'Eluru', value: 'Eluru' },
  ],
  
  'Arunachal Pradesh': [
    { label: 'Itanagar', value: 'Itanagar' },
    { label: 'Naharlagun', value: 'Naharlagun' },
    { label: 'Pasighat', value: 'Pasighat' },
    { label: 'Tawang', value: 'Tawang' },
    { label: 'Ziro', value: 'Ziro' },
    { label: 'Bomdila', value: 'Bomdila' },
    { label: 'Tezu', value: 'Tezu' },
    { label: 'Seppa', value: 'Seppa' },
  ],
  
  'Assam': [
    { label: 'Guwahati', value: 'Guwahati' },
    { label: 'Dibrugarh', value: 'Dibrugarh' },
    { label: 'Silchar', value: 'Silchar' },
    { label: 'Jorhat', value: 'Jorhat' },
    { label: 'Tezpur', value: 'Tezpur' },
    { label: 'Nagaon', value: 'Nagaon' },
    { label: 'Tinsukia', value: 'Tinsukia' },
    { label: 'Barpeta', value: 'Barpeta' },
    { label: 'Dhubri', value: 'Dhubri' },
    { label: 'Karimganj', value: 'Karimganj' },
  ],
  
  'Bihar': [
    { label: 'Patna', value: 'Patna' },
    { label: 'Gaya', value: 'Gaya' },
    { label: 'Bhagalpur', value: 'Bhagalpur' },
    { label: 'Muzaffarpur', value: 'Muzaffarpur' },
    { label: 'Purnia', value: 'Purnia' },
    { label: 'Darbhanga', value: 'Darbhanga' },
    { label: 'Arrah', value: 'Arrah' },
    { label: 'Begusarai', value: 'Begusarai' },
    { label: 'Katihar', value: 'Katihar' },
    { label: 'Munger', value: 'Munger' },
  ],
  
  'Chhattisgarh': [
    { label: 'Raipur', value: 'Raipur' },
    { label: 'Bhilai', value: 'Bhilai' },
    { label: 'Korba', value: 'Korba' },
    { label: 'Bilaspur', value: 'Bilaspur' },
    { label: 'Rajnandgaon', value: 'Rajnandgaon' },
    { label: 'Jagdalpur', value: 'Jagdalpur' },
    { label: 'Raigarh', value: 'Raigarh' },
    { label: 'Ambikapur', value: 'Ambikapur' },
    { label: 'Dhamtari', value: 'Dhamtari' },
    { label: 'Mahasamund', value: 'Mahasamund' },
  ],
  
  'Goa': [
    { label: 'Panaji', value: 'Panaji' },
    { label: 'Margao', value: 'Margao' },
    { label: 'Vasco da Gama', value: 'Vasco da Gama' },
    { label: 'Mapusa', value: 'Mapusa' },
    { label: 'Ponda', value: 'Ponda' },
    { label: 'Bicholim', value: 'Bicholim' },
    { label: 'Curchorem', value: 'Curchorem' },
    { label: 'Sanquelim', value: 'Sanquelim' },
  ],
  
  'Gujarat': [
    { label: 'Ahmedabad', value: 'Ahmedabad' },
    { label: 'Surat', value: 'Surat' },
    { label: 'Vadodara', value: 'Vadodara' },
    { label: 'Rajkot', value: 'Rajkot' },
    { label: 'Bhavnagar', value: 'Bhavnagar' },
    { label: 'Jamnagar', value: 'Jamnagar' },
    { label: 'Gandhinagar', value: 'Gandhinagar' },
    { label: 'Junagadh', value: 'Junagadh' },
    { label: 'Anand', value: 'Anand' },
    { label: 'Navsari', value: 'Navsari' },
    { label: 'Morbi', value: 'Morbi' },
    { label: 'Mehsana', value: 'Mehsana' },
    { label: 'Bharuch', value: 'Bharuch' },
    { label: 'Vapi', value: 'Vapi' },
    { label: 'Veraval', value: 'Veraval' },
  ],
  
  'Haryana': [
    { label: 'Gurugram', value: 'Gurugram' },
    { label: 'Faridabad', value: 'Faridabad' },
    { label: 'Panipat', value: 'Panipat' },
    { label: 'Ambala', value: 'Ambala' },
    { label: 'Yamunanagar', value: 'Yamunanagar' },
    { label: 'Rohtak', value: 'Rohtak' },
    { label: 'Hisar', value: 'Hisar' },
    { label: 'Karnal', value: 'Karnal' },
    { label: 'Sonipat', value: 'Sonipat' },
    { label: 'Panchkula', value: 'Panchkula' },
    { label: 'Bhiwani', value: 'Bhiwani' },
    { label: 'Sirsa', value: 'Sirsa' },
  ],
  
  'Himachal Pradesh': [
    { label: 'Shimla', value: 'Shimla' },
    { label: 'Dharamshala', value: 'Dharamshala' },
    { label: 'Solan', value: 'Solan' },
    { label: 'Mandi', value: 'Mandi' },
    { label: 'Palampur', value: 'Palampur' },
    { label: 'Baddi', value: 'Baddi' },
    { label: 'Nahan', value: 'Nahan' },
    { label: 'Una', value: 'Una' },
    { label: 'Kullu', value: 'Kullu' },
    { label: 'Hamirpur', value: 'Hamirpur' },
  ],
  
  'Jharkhand': [
    { label: 'Ranchi', value: 'Ranchi' },
    { label: 'Jamshedpur', value: 'Jamshedpur' },
    { label: 'Dhanbad', value: 'Dhanbad' },
    { label: 'Bokaro', value: 'Bokaro' },
    { label: 'Deoghar', value: 'Deoghar' },
    { label: 'Phusro', value: 'Phusro' },
    { label: 'Hazaribagh', value: 'Hazaribagh' },
    { label: 'Giridih', value: 'Giridih' },
    { label: 'Ramgarh', value: 'Ramgarh' },
    { label: 'Medininagar', value: 'Medininagar' },
  ],
  
  'Karnataka': [
    { label: 'Bengaluru', value: 'Bengaluru' },
    { label: 'Mysuru', value: 'Mysuru' },
    { label: 'Hubballi', value: 'Hubballi' },
    { label: 'Mangaluru', value: 'Mangaluru' },
    { label: 'Belagavi', value: 'Belagavi' },
    { label: 'Davangere', value: 'Davangere' },
    { label: 'Ballari', value: 'Ballari' },
    { label: 'Tumakuru', value: 'Tumakuru' },
    { label: 'Shivamogga', value: 'Shivamogga' },
    { label: 'Raichur', value: 'Raichur' },
    { label: 'Bidar', value: 'Bidar' },
    { label: 'Hosapete', value: 'Hosapete' },
    { label: 'Gadag', value: 'Gadag' },
    { label: 'Udupi', value: 'Udupi' },
  ],
  
  'Kerala': [
    { label: 'Thiruvananthapuram', value: 'Thiruvananthapuram' },
    { label: 'Kochi', value: 'Kochi' },
    { label: 'Kozhikode', value: 'Kozhikode' },
    { label: 'Thrissur', value: 'Thrissur' },
    { label: 'Alappuzha', value: 'Alappuzha' },
    { label: 'Kollam', value: 'Kollam' },
    { label: 'Palakkad', value: 'Palakkad' },
    { label: 'Kannur', value: 'Kannur' },
    { label: 'Kottayam', value: 'Kottayam' },
    { label: 'Malappuram', value: 'Malappuram' },
    { label: 'Thalassery', value: 'Thalassery' },
    { label: 'Ponnani', value: 'Ponnani' },
  ],
  
  'Madhya Pradesh': [
    { label: 'Bhopal', value: 'Bhopal' },
    { label: 'Indore', value: 'Indore' },
    { label: 'Gwalior', value: 'Gwalior' },
    { label: 'Jabalpur', value: 'Jabalpur' },
    { label: 'Ujjain', value: 'Ujjain' },
    { label: 'Sagar', value: 'Sagar' },
    { label: 'Dewas', value: 'Dewas' },
    { label: 'Satna', value: 'Satna' },
    { label: 'Ratlam', value: 'Ratlam' },
    { label: 'Rewa', value: 'Rewa' },
    { label: 'Murwara', value: 'Murwara' },
    { label: 'Singrauli', value: 'Singrauli' },
    { label: 'Burhanpur', value: 'Burhanpur' },
    { label: 'Khandwa', value: 'Khandwa' },
  ],
  
  'Maharashtra': [
    { label: 'Mumbai', value: 'Mumbai' },
    { label: 'Pune', value: 'Pune' },
    { label: 'Nagpur', value: 'Nagpur' },
    { label: 'Thane', value: 'Thane' },
    { label: 'Nashik', value: 'Nashik' },
    { label: 'Aurangabad', value: 'Aurangabad' },
    { label: 'Solapur', value: 'Solapur' },
    { label: 'Amravati', value: 'Amravati' },
    { label: 'Kolhapur', value: 'Kolhapur' },
    { label: 'Sangli', value: 'Sangli' },
    { label: 'Malegaon', value: 'Malegaon' },
    { label: 'Akola', value: 'Akola' },
    { label: 'Latur', value: 'Latur' },
    { label: 'Dhule', value: 'Dhule' },
    { label: 'Ahmednagar', value: 'Ahmednagar' },
    { label: 'Chandrapur', value: 'Chandrapur' },
    { label: 'Parbhani', value: 'Parbhani' },
    { label: 'Jalgaon', value: 'Jalgaon' },
  ],
  
  'Manipur': [
    { label: 'Imphal', value: 'Imphal' },
    { label: 'Thoubal', value: 'Thoubal' },
    { label: 'Bishnupur', value: 'Bishnupur' },
    { label: 'Churachandpur', value: 'Churachandpur' },
    { label: 'Ukhrul', value: 'Ukhrul' },
    { label: 'Senapati', value: 'Senapati' },
    { label: 'Tamenglong', value: 'Tamenglong' },
    { label: 'Jiribam', value: 'Jiribam' },
  ],
  
  'Meghalaya': [
    { label: 'Shillong', value: 'Shillong' },
    { label: 'Tura', value: 'Tura' },
    { label: 'Nongpoh', value: 'Nongpoh' },
    { label: 'Jowai', value: 'Jowai' },
    { label: 'Baghmara', value: 'Baghmara' },
    { label: 'Williamnagar', value: 'Williamnagar' },
    { label: 'Nongstoin', value: 'Nongstoin' },
    { label: 'Mawkyrwat', value: 'Mawkyrwat' },
  ],
  
  'Mizoram': [
    { label: 'Aizawl', value: 'Aizawl' },
    { label: 'Lunglei', value: 'Lunglei' },
    { label: 'Champhai', value: 'Champhai' },
    { label: 'Serchhip', value: 'Serchhip' },
    { label: 'Kolasib', value: 'Kolasib' },
    { label: 'Lawngtlai', value: 'Lawngtlai' },
    { label: 'Mamit', value: 'Mamit' },
    { label: 'Saiha', value: 'Saiha' },
  ],
  
  'Nagaland': [
    { label: 'Kohima', value: 'Kohima' },
    { label: 'Dimapur', value: 'Dimapur' },
    { label: 'Mokokchung', value: 'Mokokchung' },
    { label: 'Tuensang', value: 'Tuensang' },
    { label: 'Wokha', value: 'Wokha' },
    { label: 'Zunheboto', value: 'Zunheboto' },
    { label: 'Mon', value: 'Mon' },
    { label: 'Phek', value: 'Phek' },
  ],
  
  'Odisha': [
    { label: 'Bhubaneswar', value: 'Bhubaneswar' },
    { label: 'Cuttack', value: 'Cuttack' },
    { label: 'Rourkela', value: 'Rourkela' },
    { label: 'Berhampur', value: 'Berhampur' },
    { label: 'Sambalpur', value: 'Sambalpur' },
    { label: 'Puri', value: 'Puri' },
    { label: 'Balasore', value: 'Balasore' },
    { label: 'Bhadrak', value: 'Bhadrak' },
    { label: 'Baripada', value: 'Baripada' },
    { label: 'Jharsuguda', value: 'Jharsuguda' },
  ],
  
  'Punjab': [
    { label: 'Ludhiana', value: 'Ludhiana' },
    { label: 'Amritsar', value: 'Amritsar' },
    { label: 'Jalandhar', value: 'Jalandhar' },
    { label: 'Patiala', value: 'Patiala' },
    { label: 'Bathinda', value: 'Bathinda' },
    { label: 'Mohali', value: 'Mohali' },
    { label: 'Firozpur', value: 'Firozpur' },
    { label: 'Batala', value: 'Batala' },
    { label: 'Pathankot', value: 'Pathankot' },
    { label: 'Moga', value: 'Moga' },
    { label: 'Abohar', value: 'Abohar' },
    { label: 'Malerkotla', value: 'Malerkotla' },
  ],
  
  'Rajasthan': [
    { label: 'Jaipur', value: 'Jaipur' },
    { label: 'Jodhpur', value: 'Jodhpur' },
    { label: 'Kota', value: 'Kota' },
    { label: 'Bikaner', value: 'Bikaner' },
    { label: 'Udaipur', value: 'Udaipur' },
    { label: 'Ajmer', value: 'Ajmer' },
    { label: 'Bhilwara', value: 'Bhilwara' },
    { label: 'Alwar', value: 'Alwar' },
    { label: 'Bharatpur', value: 'Bharatpur' },
    { label: 'Pali', value: 'Pali' },
    { label: 'Barmer', value: 'Barmer' },
    { label: 'Sikar', value: 'Sikar' },
    { label: 'Tonk', value: 'Tonk' },
    { label: 'Kishangarh', value: 'Kishangarh' },
  ],
  
  'Sikkim': [
    { label: 'Gangtok', value: 'Gangtok' },
    { label: 'Namchi', value: 'Namchi' },
    { label: 'Gyalshing', value: 'Gyalshing' },
    { label: 'Mangan', value: 'Mangan' },
    { label: 'Jorethang', value: 'Jorethang' },
    { label: 'Nayabazar', value: 'Nayabazar' },
    { label: 'Rangpo', value: 'Rangpo' },
    { label: 'Singtam', value: 'Singtam' },
  ],
  
  'Tamil Nadu': [
    { label: 'Chennai', value: 'Chennai' },
    { label: 'Coimbatore', value: 'Coimbatore' },
    { label: 'Madurai', value: 'Madurai' },
    { label: 'Tiruchirappalli', value: 'Tiruchirappalli' },
    { label: 'Salem', value: 'Salem' },
    { label: 'Tirunelveli', value: 'Tirunelveli' },
    { label: 'Tiruppur', value: 'Tiruppur' },
    { label: 'Vellore', value: 'Vellore' },
    { label: 'Erode', value: 'Erode' },
    { label: 'Thoothukkudi', value: 'Thoothukkudi' },
    { label: 'Dindigul', value: 'Dindigul' },
    { label: 'Thanjavur', value: 'Thanjavur' },
    { label: 'Ranipet', value: 'Ranipet' },
    { label: 'Sivakasi', value: 'Sivakasi' },
    { label: 'Karur', value: 'Karur' },
    { label: 'Udhagamandalam', value: 'Udhagamandalam' },
  ],
  
  'Telangana': [
    { label: 'Hyderabad', value: 'Hyderabad' },
    { label: 'Warangal', value: 'Warangal' },
    { label: 'Nizamabad', value: 'Nizamabad' },
    { label: 'Karimnagar', value: 'Karimnagar' },
    { label: 'Ramagundam', value: 'Ramagundam' },
    { label: 'Khammam', value: 'Khammam' },
    { label: 'Mahbubnagar', value: 'Mahbubnagar' },
    { label: 'Nalgonda', value: 'Nalgonda' },
    { label: 'Adilabad', value: 'Adilabad' },
    { label: 'Suryapet', value: 'Suryapet' },
    { label: 'Miryalaguda', value: 'Miryalaguda' },
    { label: 'Jagtial', value: 'Jagtial' },
  ],
  
  'Tripura': [
    { label: 'Agartala', value: 'Agartala' },
    { label: 'Dharmanagar', value: 'Dharmanagar' },
    { label: 'Udaipur', value: 'Udaipur' },
    { label: 'Kailasahar', value: 'Kailasahar' },
    { label: 'Belonia', value: 'Belonia' },
    { label: 'Khowai', value: 'Khowai' },
    { label: 'Ambassa', value: 'Ambassa' },
    { label: 'Ranir Bazar', value: 'Ranir Bazar' },
  ],
  
  'Uttar Pradesh': [
    { label: 'Lucknow', value: 'Lucknow' },
    { label: 'Kanpur', value: 'Kanpur' },
    { label: 'Ghaziabad', value: 'Ghaziabad' },
    { label: 'Agra', value: 'Agra' },
    { label: 'Varanasi', value: 'Varanasi' },
    { label: 'Meerut', value: 'Meerut' },
    { label: 'Allahabad', value: 'Allahabad' },
    { label: 'Bareilly', value: 'Bareilly' },
    { label: 'Aligarh', value: 'Aligarh' },
    { label: 'Moradabad', value: 'Moradabad' },
    { label: 'Saharanpur', value: 'Saharanpur' },
    { label: 'Gorakhpur', value: 'Gorakhpur' },
    { label: 'Noida', value: 'Noida' },
    { label: 'Firozabad', value: 'Firozabad' },
    { label: 'Jhansi', value: 'Jhansi' },
    { label: 'Muzaffarnagar', value: 'Muzaffarnagar' },
    { label: 'Mathura', value: 'Mathura' },
    { label: 'Rampur', value: 'Rampur' },
  ],
  
  'Uttarakhand': [
    { label: 'Dehradun', value: 'Dehradun' },
    { label: 'Haridwar', value: 'Haridwar' },
    { label: 'Roorkee', value: 'Roorkee' },
    { label: 'Haldwani', value: 'Haldwani' },
    { label: 'Rudrapur', value: 'Rudrapur' },
    { label: 'Kashipur', value: 'Kashipur' },
    { label: 'Rishikesh', value: 'Rishikesh' },
    { label: 'Ramnagar', value: 'Ramnagar' },
    { label: 'Pithoragarh', value: 'Pithoragarh' },
    { label: 'Almora', value: 'Almora' },
  ],
  
  'West Bengal': [
    { label: 'Kolkata', value: 'Kolkata' },
    { label: 'Howrah', value: 'Howrah' },
    { label: 'Durgapur', value: 'Durgapur' },
    { label: 'Asansol', value: 'Asansol' },
    { label: 'Siliguri', value: 'Siliguri' },
    { label: 'Malda', value: 'Malda' },
    { label: 'Baharampur', value: 'Baharampur' },
    { label: 'Habra', value: 'Habra' },
    { label: 'Kharagpur', value: 'Kharagpur' },
    { label: 'Shantipur', value: 'Shantipur' },
    { label: 'Dankuni', value: 'Dankuni' },
    { label: 'Dhulian', value: 'Dhulian' },
    { label: 'Ranaghat', value: 'Ranaghat' },
    { label: 'Haldia', value: 'Haldia' },
    { label: 'Raiganj', value: 'Raiganj' },
  ],
  
  // Union Territories
  'Andaman and Nicobar Islands': [
    { label: 'Port Blair', value: 'Port Blair' },
    { label: 'Bamboo Flat', value: 'Bamboo Flat' },
    { label: 'Garacharma', value: 'Garacharma' },
    { label: 'Diglipur', value: 'Diglipur' },
    { label: 'Car Nicobar', value: 'Car Nicobar' },
    { label: 'Mayabunder', value: 'Mayabunder' },
    { label: 'Campbell Bay', value: 'Campbell Bay' },
    { label: 'Haddo', value: 'Haddo' },
  ],
  
  'Chandigarh': [
    { label: 'Chandigarh', value: 'Chandigarh' },
    { label: 'Sector 17', value: 'Sector 17' },
    { label: 'Sector 22', value: 'Sector 22' },
    { label: 'Sector 35', value: 'Sector 35' },
    { label: 'Mani Majra', value: 'Mani Majra' },
  ],
  
  'Dadra and Nagar Haveli and Daman and Diu': [
    { label: 'Daman', value: 'Daman' },
    { label: 'Diu', value: 'Diu' },
    { label: 'Silvassa', value: 'Silvassa' },
    { label: 'Naroli', value: 'Naroli' },
    { label: 'Dadra', value: 'Dadra' },
    { label: 'Nagar Haveli', value: 'Nagar Haveli' },
  ],
  
  'Delhi': [
    { label: 'New Delhi', value: 'New Delhi' },
    { label: 'Delhi', value: 'Delhi' },
    { label: 'Dwarka', value: 'Dwarka' },
    { label: 'Rohini', value: 'Rohini' },
    { label: 'Pitampura', value: 'Pitampura' },
    { label: 'Lajpat Nagar', value: 'Lajpat Nagar' },
    { label: 'Karol Bagh', value: 'Karol Bagh' },
    { label: 'Connaught Place', value: 'Connaught Place' },
    { label: 'Janakpuri', value: 'Janakpuri' },
    { label: 'Vasant Kunj', value: 'Vasant Kunj' },
    { label: 'Saket', value: 'Saket' },
    { label: 'Greater Kailash', value: 'Greater Kailash' },
    { label: 'Preet Vihar', value: 'Preet Vihar' },
    { label: 'Mayur Vihar', value: 'Mayur Vihar' },
  ],
  
  'Jammu and Kashmir': [
    { label: 'Srinagar', value: 'Srinagar' },
    { label: 'Jammu', value: 'Jammu' },
    { label: 'Baramulla', value: 'Baramulla' },
    { label: 'Anantnag', value: 'Anantnag' },
    { label: 'Sopore', value: 'Sopore' },
    { label: 'KathuaKathua', value: 'Kathua' },
    { label: 'Udhampur', value: 'Udhampur' },
    { label: 'Punch', value: 'Punch' },
    { label: 'Rajauri', value: 'Rajauri' },
    { label: 'Kupwara', value: 'Kupwara' },
    { label: 'Budgam', value: 'Budgam' },
    { label: 'Ganderbal', value: 'Ganderbal' },
  ],
  
  'Ladakh': [
    { label: 'Leh', value: 'Leh' },
    { label: 'Kargil', value: 'Kargil' },
    { label: 'Nubra', value: 'Nubra' },
    { label: 'Zanskar', value: 'Zanskar' },
    { label: 'Diskit', value: 'Diskit' },
    { label: 'Padum', value: 'Padum' },
    { label: 'Khaltse', value: 'Khaltse' },
    { label: 'Dras', value: 'Dras' },
  ],
  
  'Lakshadweep': [
    { label: 'Kavaratti', value: 'Kavaratti' },
    { label: 'Agatti', value: 'Agatti' },
    { label: 'Minicoy', value: 'Minicoy' },
    { label: 'Amini', value: 'Amini' },
    { label: 'Androth', value: 'Androth' },
    { label: 'Kalpeni', value: 'Kalpeni' },
    { label: 'Kadmat', value: 'Kadmat' },
    { label: 'Kiltan', value: 'Kiltan' },
  ],
  
  'Puducherry': [
    { label: 'Puducherry', value: 'Puducherry' },
    { label: 'Karaikal', value: 'Karaikal' },
    { label: 'Yanam', value: 'Yanam' },
    { label: 'Mahe', value: 'Mahe' },
    { label: 'Villianur', value: 'Villianur' },
    { label: 'Ariyankuppam', value: 'Ariyankuppam' },
    { label: 'Mannadipet', value: 'Mannadipet' },
    { label: 'Bahour', value: 'Bahour' },
  ],
};